version: "3"

services:
  nginx:
    image : nginx
    container_name : nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
    depends_on:
      - flask

  flask:
    build: flask
    container_name : flask
#    volumes:
#      - ./log/flask/gunicorn_access.log:/var/log/gunicorn_access.log
#      - ./log/flask/gunicorn_error.log:/var/log/gunicorn_error.log
    expose:
      - 5000
